=== calliope1/BudgetApp/src/server/schemata/data.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "required": [ "id", "amount", "description", "date" ],
    "properties": {
      "id": {
        "type": "string",
        "pattern": "^[a-fA-F0-9]+$"
      },
      "amount": {
        "type": "number",
        "minimum": 0
      },
      "description": {
        "type": "string"
      },
      "date": {
        "type": "string",
        "format": "date"
      }
    },
    "additionalProperties": false
  }
}

=== calliope1/BudgetApp/src/server/data/data.json
[
  {
    "amount": 3.79,
    "date": "2025-08-28",
    "description": "Groceries",
    "id": "00a3e0099b445d04548a45f0fead2e25"
  },
  {
    "amount": 10.23,
    "date": "2025-08-26",
    "description": "Clipper charger and command strips",
    "id": "ba7a20df91f649b4bb45a8b1e0bd4e33"
  },
  {
    "amount": 4.98,
    "date": "2025-08-25",
    "description": "Spirit level",
    "id": "c4926ea87e186e19f51482fd5e66765d"
  },
  {
    "amount": 4.0,
    "date": "2025-08-29",
    "description": "Lara bus",
    "id": "439eea70c480a5744f8eb125eb90d44b"
  },
  {
    "amount": 7.0,
    "date": "2025-08-29",
    "description": "Lara tea and cakes",
    "id": "18f65687e2300c0d42742caa075ce769"
  },
  {
    "amount": 8.4,
    "date": "2025-08-26",
    "description": "Lunch with Dylan",
    "id": "a43cccceeb02adcc58568860f34d1f49"
  },
  {
    "amount": 2.89,
    "date": "2025-08-31",
    "description": "Bread",
    "id": "12836eee8d1719b77525b6a326b8f261"
  },
  {
    "amount": 42.12,
    "date": "2025-08-31",
    "description": "Sainsburys",
    "id": "2fe4d74a746fcd38caa702c3de4d078b"
  },
  {
    "amount": 9.9,
    "date": "2025-09-01",
    "description": "Mailing keys",
    "id": "d83ec64009cb0b02dd31f2d790143b6f"
  },
  {
    "amount": 1.49,
    "date": "2025-09-01",
    "description": "Bread",
    "id": "f9ee8798d40d5158db8433224de22a62"
  },
  {
    "amount": 2.1,
    "date": "2025-09-01",
    "description": "Tofu",
    "id": "10c4d7eb15655c13a49bb71ade562d53"
  },
  {
    "amount": 6.79,
    "date": "2025-09-02",
    "description": "Misc grocs",
    "id": "d18740eda38cf6d64c9c1c069b72b21e"
  },
  {
    "amount": 2.0,
    "date": "2025-09-02",
    "description": "Bus ticket",
    "id": "3188fe2e2ae4141e6efcd693e0a47407"
  },
  {
    "amount": 4.3,
    "date": "2025-09-03",
    "description": "Drinks",
    "id": "a4ba18a4bcb6146b850eed7dc1b3626c"
  },
  {
    "amount": 3.04,
    "date": "2025-09-04",
    "description": "Grocs",
    "id": "c22eff09893d3aaf0d306edbd7f7c4a0"
  },
  {
    "amount": 16.75,
    "date": "2025-09-04",
    "description": "Silksong",
    "id": "4a8e545d6ed7d127fe032235427bfc19"
  },
  {
    "amount": 3.6,
    "date": "2025-09-06",
    "description": "Coffee ",
    "id": "d1f2794883b505d40560098081c2d909"
  },
  {
    "amount": 36.39,
    "date": "2025-09-06",
    "description": "Grocs",
    "id": "619a9a76ccb76bd2fe718fa960798f0e"
  },
  {
    "amount": 22.5,
    "date": "2025-09-07",
    "description": "Clothes ",
    "id": "f9947ad311ee5dac145a32880c89742d"
  },
  {
    "amount": 7.5,
    "date": "2025-09-09",
    "description": "Tea treats",
    "id": "f3589643c8f8e317fe6034b3db7cec00"
  },
  {
    "amount": 2.85,
    "date": "2025-09-10",
    "description": "Train tickets ",
    "id": "bd28d470ec27498e8ee098b1819ee09e"
  },
  {
    "amount": 2.3,
    "date": "2025-09-12",
    "description": "Bus",
    "id": "ca3be1bf2ba92e027577d6fc9634ae1e"
  },
  {
    "amount": 3.75,
    "date": "2025-09-13",
    "description": "Coffee treat",
    "id": "5e71e2ac6172e20df25dccede231244b"
  },
  {
    "amount": 3.75,
    "date": "2025-09-13",
    "description": "Grocs",
    "id": "7fcecef306e7668151e13d508107c412"
  },
  {
    "amount": 6.0,
    "date": "2025-09-13",
    "description": "Fruits",
    "id": "e668173f2ca2c4bd4135f2b055512dd2"
  },
  {
    "amount": 2.75,
    "date": "2025-09-14",
    "description": "Crisps",
    "id": "3302cc946c3ede5ddd26b328d48c73c5"
  },
  {
    "amount": 42.21,
    "date": "2025-09-14",
    "description": "Grocs ",
    "id": "c50593d7b04db564cdc0091e95f581cb"
  },
  {
    "amount": 19.56,
    "date": "2025-09-14",
    "description": "Amazon",
    "id": "53c4d0640954b8df677ae5fff3b7e987"
  },
  {
    "amount": 2.3,
    "date": "2025-09-15",
    "description": "Bus",
    "id": "28ac06b1e950ac772b3d4a5edbcd1de4"
  }
]
